version: "3.8"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:alpine
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - 9090:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock